### ISSUE TITLE
Possible Bug: 100% disk activity on large files?

### ISSUE THREAD

**Issue by heikoh81** [bailey27/cppcryptfs#34]
Hi,
I noticed a possible bug that I cannot locate. It might come from Dokany or cppcryptfs.
It happens if I copy large files (~6-8 GB each) to an encrypted USB Seagate HDD.
The first few files write ok (but very slow at 16 MB/s). The more I copy, the slower write speeds get. Disk activity goes up to 100%, Speed drops to 2 MB/s. After several minutes writing is nearly impossible.

This happens with different external drives and on different PCs (1 with Win10 LTSB 1604, 1 with Win 8.1).
Dokany is 1.2.0.1000, cppcryptfs is 1.4.0.19.
It does not happen with VeryCrypt on the same PCs and the same USB Disks, and speed is 50 MB/s with VeryCrypt. Unencrypted write speed to these external drives is ~ 100-120 MB/s.
The USB drives are very new, and have no S.M.A.R.T warnings.

The problem only occurs while writing, never while reading. Reading also performs at 50 MB/s.
At the moment I have to go back to VeraCrypt for my large file use scenarios, while I can use gocryptfs with 1000s of small files without performance issues. I'd prefer gocryptfs for the future because it is file based and not container based!

Best regards,
Heiko

**Comment by bailey27** [comment]
I'm sorry but I wasn't able to reproduce this problem.

cppcryptfs should perform the same as VeraCrypt on large files.  But VeraCrypt should perform better than cppcryptfs when dealing with lots of small files.  You seem to be observing the exact opposite.

I tried using up to ten 8gb files of random data. I tried my C: ssd, my internal mechanical D: drive, an ssd in a usb 3.0 enclosure and a mechanical drive in a usb 3.0 enclosure.  

In every case, the performance of cppcryptfs was almost the same as VeraCrypt.

Could you try to reproduce the problem using dokany mirror?

It's a command line program in C:\Program Files\Dokan\Dokan Library-1.2.0\sample\mirror

e.g. 

mirror /l x: /r d:\tmp

This would make drive letter X: mirror the contents of directory d:\tmp

It asks to be run as administrator but works anyway without administrator privileges.

**Comment by heikoh81** [comment]
Thanks for your tests. This is strange, indeed.
I even disable Avira FreeAV Realtime Monitoring during copy, to exclude this as a possible cause.

I'd try the mirror command.
I have these questions:
Does d:\tmp have to exist?
Does drive x have to exist? I use the letter X for gocryptfs and VeraCrypt mounts - what if a drive x is already mounted, will data be overwritten?
I don't want to lose data...

Best regards,
Heiko

**Comment by heikoh81** [comment]
I did some further testing.

With Veracrypt, I get Windwos Error 666 if the Container-File (dynamic growth) gets to big (> 1,3 TB).
Windows disk analyses shows 99% fragmentation. Although I could not Google any evidence with VeraCrypt, this seems to be a problem on my side.

So my only option is to go with gocryptfs.
I reformatted my 6 TB / 8 TB USB-HDDs with exFAT (would prefer ReFS, but not available on Win 10 1607 LTSB).
Now all my problems are gone, disk activity maxes at 95%, write speed is up to 120 MB/s with cppcryptfs (average speed is 85 MB/s, though, but still very very good).

So the problem seems to be NTFS, although I always though this is the file system to go on Windows systems.

I'll continue with exFAT on external drives from now on.
Another advantage: I can mount those disks on any Linux and use gocryptfs there!

**Comment by bailey27** [comment]
That's great.  exFAT is a good filesystem.  You can have paths over 32,000 characters long just like NTFS.

I've updated the Readme.

**Comment by ccchan234** [comment]
major update:
When I want to copy 4TB files from NTFS on truecrypt partition (on USB raid 1 box, SATA HDD) to cppcfs on exFAT on 4TB USB drive.
while I only copied about 1.2TB (by beyond compare 4), it say that the target disk drive is only have 109MB left.

So even I tried this copy movement since 20181225, I still dont have the work done.
May be I will try back using NTFS... not sure what's the problem.
(I know the encrypted files will be larger than the original files but 1.2TB cant occupy 4TB drive i think)

thanks

**Comment by bailey27** [comment]
I have no idea why you see a different disk space usage outside of cppcryptfs vs. doing drive property on the mounted cppcryptfs drive letter.

All I do when Dokany asks for the free space amount is to call the Windows API function GetDiskFreeSpaceExW() on the actual drive letter where the encrypted filesystem is.  I don't see how the sizes could differ.

I think you should maybe try Robocopy.  It is from Microsoft and comes with Windows.  It handles very long paths.

It is command line only, though.

It comes with ordinary Windows, not just Windows server.

https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/robocopy

https://en.wikipedia.org/wiki/Robocopy

**Comment by ccchan234** [comment]
thanks for reply.

1. using NTFS + freefilesync seems working overnite so I stopped playing with exFAT. (also stopped using
beyond compare to copy)

2. I am still in progress of copying 4TB files into cppcfs on NTFS, will report if finally success (hope so) or not.

Happy new year.

**Comment by ccchan234** [comment]
hi~
it appears the problem could be due to beyond compare 4.
And trying to update to 1.4.0.21 may be a solution if anyone still encounters.
Mean while thanks author 's concern and think this issue could be closed, thanks.

**Comment by heikoh81** [comment]
I still don't think that this program is Software-related.
I had 100% disk activity on copying with Windows Explorer, SpeedCommander, Goodsync and FreeFileSync.

I think that heavy fragmentation takes place on NTFS-drives. To me it seems that this has started with HDDs > 5 TB. And on those drives I normally store large files 4 GB+ and I do linear writing - so fragmentation should be not problem at all.

See my link postet above:
https://blogs.msdn.microsoft.com/psssql/2015/06/10/operating-system-error-665-file-system-limitation-not-just-for-dbcc-anymore/

I have no problems any more using exFAT.
I have not tried ext4, as I don't use my large HDDs with Linux.

**Comment by ccchan234** [comment]
> I still don't think that this problem is Software-related.
> I had 100% disk activity on copying with Windows Explorer, SpeedCommander, Goodsync and FreeFileSync.
> 
> I think that heavy fragmentation takes place on NTFS-drives. To me it seems that this has started with HDDs > 5 TB. And on those drives I normally store large files 4 GB+ and I do linear writing - so fragmentation should be no problem at all.
> I'm no expert on file systems, just a heavy user. All I have read is that large files or large drives should be no problem for NTFS, but in my experience there were problems on various PCs with various Win versions.
> 
> See my link postet above:
> https://blogs.msdn.microsoft.com/psssql/2015/06/10/operating-system-error-665-file-system-limitation-not-just-for-dbcc-anymore/
> 
> I have no problems any more using exFAT.
> I have not tried ext4, as I don't use my large HDDs with Linux.

Hi
I dont know if they are the same problem.
Yet just share above that experience while I copy 4TB from truecrypt to cppcryptfs.
I cant do that with beyond compare, and it's significantly slower than not using cppcryptfs(due to dokany?), and it can be done with files > 100GB, while I updated to 1.4.0.21 and use free file sync.

thanks.
